shallow_clone: true

# version format
version: 1.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

cache:
  - SDelete-Gui\packages

configuration: Release

# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


environment:
  sign_tool: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe'
  artifact_path: 'C:\projects\sdelete-gui\SDelete-Gui\bin\Release\SDelete-Gui.exe'
  timestamp_url: http://timestamp.verisign.com/scripts/timstamp.dll
  pfx_file: 'C:\projects\sdelete-gui\tulpep.pfx'
  pfx_password:
    secure: yfky3xGsKE0Kwe2xOHB2sQ==


after_build:
  - cmd: '%sign_tool% sign /f %pfx_file% /p %pfx_passfword% /t %timestamp_url% %artifact_path%'

artifacts:
  - path: '**\bin\Release\SDelete-Gui.exe'
    name: SDelete-Gui.exe
